status:
  servername: §r§eSun Proxy§r
  playercount: 0
  maxplayers: 50
  showversion: false
hub:
  address: 127.0.0.1
  port: 19133
proxy:
  port: 19132
  xboxauthentication: false
  ipforwarding: false
  transfercommand:
    enabled: false
    servers:
      example:
        address: 127.0.0.1
        port: 19134
  loadbalancer:
    enabled: true
    balancers:
    - address: 127.0.0.1
      port: 19134
  statuscommand: true
  ppof:
    enabled: true
    port: 8080
  logger:
    file: sun.log
    debug: false
  motdforward: false
tcp:
  enabled: false
  key: XhvMUq7jm1TE39pwprQrjhipZ
